name: Build and deploy to a Public Azure Function App
on:
  push:
    branches:
      - main
    paths:
      - 'ExampleAzureFunctions/**'
      - 'DevOps/**'
      - '.github/workflows/az-deployment.yml'
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: 'example-az-func'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  DOTNET_VERSION: '8.0.x'

jobs:
  build-and-deploy:
    runs-on: [self-hosted, Windows]
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3.6.0

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Resolve Project Dependencies Using Dotnet'
        shell: pwsh
        run: |
          dotnet build --configuration Release --output ./output

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: '${{ env.AZURE_FUNCTIONAPP_NAME }}'
          slot-name: 'Production'
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}