name: Deploy a Public Azure Function App
on:
  push:
    branches:
      - main
    paths:
      - 'ExampleAzureFunctions/**'
      - 'DevOps/**'
      - '.github/workflows/azure-deployment.yml'
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: 'example-az-func'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '${{ github.workspace }}\build-packages'
  PROJECT_TARGET_PATH: './ExampleAzureFunctions/ExampleAzureFunctions.csproj'
  BUILD_NAME: 'ExampleAzFunc'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - uses: nhatthaiquang-agilityio/Terraform-CI-CD/.github/actions/build-package-dotnet@main
        id: build-package
        with:
          build-target-path: ${{ env.PROJECT_TARGET_PATH }}
          build-name: ${{ env.BUILD_NAME }}

  deploy:
    runs-on: [self-hosted, Windows]
    environment: test
    needs: [build]
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: 'drop'
          path: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

      # You can also make use of a ZIP GitHub Action
      - name: "Create ZIP"
        shell: pwsh
        run: |
          Set-Location ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          Get-ChildItem $pwd | Compress-Archive -Destination .\backend.zip

      - name: 'Deploy the ZIP to the app'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: ./backend.zip

      # - name: 'Run Azure Functions Action'
      #   uses: Azure/functions-action@v1
      #   id: azure-functions
      #   with:
      #     app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
      #     slot-name: 'Production'
      #     package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
      #     publish-profile: '${{ secrets.AZURE_PUBLISH_PROFILE }}'