name: Deploy Azure Function App
on:
  push:
    branches:
      - main
    paths:
      - 'ExampleAzureFunctions/**'
      - 'DevOps/**'
      - '.github/workflows/deployment.yml'
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: 'example-az-func'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './ExampleAzureFunctions'
  TERRAFORM_FILENAME: 'infrastructure.tfstate'
  TERRAFORM_WORKING_DIRECTORY: './DevOps/Terraform/Infrastructures'
  TERRAFORM_STORAGE_ACCOUNT: 'tfstateexampleazfunc'
  TERRAFORM_CONTAINER_NAME: 'tfstatecontainer'
  TERRAFORM_RESOURCE_GROUP_NAME: 'RG-ExampleAzureFunctions'
  PROJECT_TARGET_PATH: './ExampleAzureFunctions/ExampleAzureFunctions.csproj'
  SOLUTION_PATH: 'ExampleAzureFunctions.sln'
  BUILD_NAME: 'ExampleAzureFunctions'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - uses: nhatthaiquang-agilityio/Terraform-CI-CD/.github/actions/build-package-dotnet@main
        id: build-package
        with:
          solution-path: ${{ env.SOLUTION_PATH }}
          build-target-path: ${{ env.PROJECT_TARGET_PATH }}
          build-name: ${{ env.BUILD_NAME }}

  setup-infrastructure-on-test:
    runs-on: windows-latest
    environment: test
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - uses: nhatthaiquang-agilityio/Terraform-CI-CD/.github/actions/terraform@main
        id: run-terraform
        with:
          working-directory: ${{ env.TERRAFORM_WORKING_DIRECTORY }}
          environment: 'test'
          arm-client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          arm-client-id: ${{ secrets.AZURE_CLIENT_ID }}
          arm-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          arm-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          terraform-resource-group-name: ${{ env.TERRAFORM_RESOURCE_GROUP_NAME }}
          terraform-storage-account: ${{ env.TERRAFORM_STORAGE_ACCOUNT }}
          terraform-container-name: ${{ env.TERRAFORM_CONTAINER_NAME }}
          terraform-filename: 'test.${{ env.TERRAFORM_FILENAME }}'

  deploy:
    runs-on: [self-hosted, Windows, X64]
    environment: test
    needs: [build, setup-infrastructure-on-test]
    steps:
    - name: 'Deploy Azure Function App'
      uses: nhatthaiquang-agilityio/Terraform-CI-CD/.github/actions/deploy-azure-function@main
      id: azure-functions
      with:
        azure-function-app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        azure-function-package-path: ' ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        arm-credentials: ${{ secrets.AZURE_CREDENTIALS }}